import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Feed from "@/components/Feed";
import Widgets from "@/components/Widgets";

export default function Home({newsResults, RandomUserResults}) {
  console.log();
  return (
    <>
      <Head>
        <title>Twitter app clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main className="m-auto flex min-h-screen mx-auto ">
        {/* sidebar section*/}
        <Sidebar />

        {/* Feed section  */}
        <Feed/>

        {/* widgets section  */}
        <Widgets  newsResults={newsResults.articles} RandomUserResults={RandomUserResults.results}/>
        {/* popup model box  */}

      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json').then((res) => res.json());
  // who to follow section 

  const RandomUserResults = await fetch('https://randomuser.me/api/?results=50&inc=name,login,picture').then((res) => res.json());
  return {
    props:{
      newsResults,
      RandomUserResults,
    }
  }
}

